module heromodels

import freeflowuniverse.herolib.data.encoder
import crypto.md5
import freeflowuniverse.herolib.data.ourtime
import freeflowuniverse.herolib.core.redisclient
import freeflowuniverse.herolib.hero.db

@[heap]
pub struct Comment {
	db.Base
pub mut:
	// id           u32
	comment string
	parent  u32 // id of parent comment if any, 0 means none
	author  u32 // links to user
}

//////////TO BE GENERATED BY AI////////////////////////////////
///BASIC CRUD FUNCTIONS

pub struct DBComments {
pub mut:
	db &db.DB @[skip; str: skip]
}

pub fn (self Comment) type_name() string {
	return 'comments'
}

pub fn (self Comment) dump() ![]u8 {
	// Create a new encoder
	mut e := encoder.new()
	e.add_u8(1)
	e.add_u32(self.id)
	e.add_string(self.comment)
	e.add_u32(self.parent)
	e.add_u32(self.author)
	return e.data
}

pub fn (mut self DBComments) load(data []u8) !Comment {
	// Create a new decoder
	mut e := encoder.decoder_new(data)
	version := e.get_u8()!
	if version != 1 {
		panic('wrong version in comment load')
	}
	mut comment := Comment{}
	comment.id = e.get_u32()!
	comment.comment = e.get_string()!
	comment.parent = e.get_u32()!
	comment.author = e.get_u32()!
	return comment
}

@[params]
pub struct CommentArg {
pub mut:
	comment string @[required]
	parent  u32
	author  u32
}

// get new comment, not from the DB
pub fn (mut self DBComments) new(args CommentArg) !Comment {
	mut o := Comment{
		comment:    args.comment
		parent:     args.parent
		updated_at: ourtime.now().unix()
		author:     args.author
	}
	return o
}

pub fn (mut self DBComments) set(o Comment) !u32 {
	// Use openrpcserver set function which now returns the ID
	return self.db.set[Comment](o)!
}

pub fn (mut self DBComments) delete(id u32) ! {
	self.db.delete[Comment](id)!
}

pub fn (mut self DBComments) exist(id u32) !bool {
	return self.db.exists[Comment](id)!
}

pub fn (mut self DBComments) get(id u32) !Comment {
	return self.load(self.db.get_data[Comment](id)!)!
}

pub fn (mut self DBComments) list() ![]Comment {
	return self.db.list[Comment]()!.map(self.load(self.db.get_data[Comment](it)!)!)
}
