module heromodels

import freeflowuniverse.herolib.data.encoder
import freeflowuniverse.herolib.data.ourtime
import freeflowuniverse.herolib.hero.db

@[heap]
pub struct Comment {
	db.Base
pub mut:
	// id           u32
	comment string
	parent  u32 // id of parent comment if any, 0 means none
	author  u32 // links to user
}

//////////TO BE GENERATED BY AI////////////////////////////////
///BASIC CRUD FUNCTIONS

pub struct DBComments {
pub mut:
	db &db.DB @[skip; str: skip]
}

pub fn (self Comment) type_name() string {
	return 'comments'
}

pub fn (self Comment) dump(mut e encoder.Encoder) ! {
	e.add_string(self.comment)
	e.add_u32(self.parent)
	e.add_u32(self.author)
}

fn (mut self DBComments) load(mut o Comment, mut e encoder.Decoder) ! {
	o.comment = e.get_string()!
	o.parent = e.get_u32()!
	o.author = e.get_u32()!
}

@[params]
pub struct CommentArg {
pub mut:
	comment string @[required]
	parent  u32
	author  u32
}

// get new comment, not from the DB
pub fn (mut self DBComments) new(args CommentArg) !Comment {
	mut o := Comment{
		comment:    args.comment
		parent:     args.parent
		updated_at: ourtime.now().unix()
		author:     args.author
	}
	return o
}

pub fn (mut self DBComments) set(o Comment) !u32 {
	// Use openrpcserver set function which now returns the ID
	return self.db.set[Comment](o)!
}

pub fn (mut self DBComments) delete(id u32) ! {
	self.db.delete[Comment](id)!
}

pub fn (mut self DBComments) exist(id u32) !bool {
	return self.db.exists[Comment](id)!
}

pub fn (mut self DBComments) get(id u32) !Comment {
	mut o, data := self.db.get_data[Comment](id)!
	mut e_decoder := encoder.decoder_new(data)
	self.load(mut o, mut e_decoder)!
	return o
}

pub fn (mut self DBComments) list() ![]Comment {
	return self.db.list[Comment]()!.map(self.get(it)!)
}
