name: Build on Linux & Run tests

permissions:
  contents: write

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref_name }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup V
        run: |
          # Updating man-db takes a long time on every run. We don't need it
          sudo apt-get remove -y --purge man-db
          ./scripts/install_v.sh

      - name: Setup Herolib from current branch
        run: |
          # Create necessary directories
          mkdir -p ~/.vmodules/incubaid
          # Create symlink to current code
          ln -s $(pwd)/lib ~/.vmodules/incubaid/herolib
          echo "Herolib symlink created to $(pwd)/lib"

      - name: Do all the basic tests
        run: ./test_basic.vsh
